version: '3'

vars:
  HOSTNAME:
    sh: hostname
  ARGS: "--sudo --upgrade --impure --flake .#{{ .HOSTNAME }}"
  VERBOSE:
    sh: '[[ "$LOG_LEVEL" == "debug" ]] && echo "-v" || true'

tasks:
  build:
    cmds:
      - nixos-rebuild build {{ .ARGS }} {{ .VERBOSE }} {{ .CLI_ARGS }}

  build:test:
    cmds:
      - nixos-rebuild dry-build {{ .ARGS }} -v {{ .CLI_ARGS }}

  update:
    cmds:
      - sudo nix flake update {{ .VERBOSE }}

  upgrade:
    deps:
      - update
    cmds:
      - nixos-rebuild switch {{ .ARGS }} {{ .VERBOSE }} {{ .CLI_ARGS }}

  clean:
    cmds:
      - nix-collect-garbage
      - nix-collect-garbage -d
      - nix-store --optimize
      - sudo nix-collect-garbage -d
      - task: upgrade

  firmware:update:
    cmds:
      - sudo fwupdmgr refresh --force
      - sudo fwupdmgr get-updates
      - sudo fwupdmgr update
