{
  config,
  lib,
  pkgs,
  ...
}:
let
  cfg = config.core.kernel;

  # Table of frozen nixpkgs revisions, one per kernel series, generated by
  # `task kernel:pin`. nixpkgs replaces EOL kernels with a bare `throw`, so the
  # package is gone rather than merely masked and no allowBroken /
  # permittedInsecurePackages escape hatch applies.
  #
  # Nix cannot discover these revisions during pure evaluation, so they are
  # generated rather than looked up at eval time. Refresh the table
  # periodically; every series is then already pinned at the point a host turns
  # out to need one. Fetching happens here rather than through a flake input, so
  # the mechanism is this module plus its JSON and nothing in flake.nix.
  pins = builtins.fromJSON (builtins.readFile ./kernel-pins.json);

  # nixpkgs only carries series-level attributes (linux_7_1), so a full version
  # selects by its first two components and is then checked against the patch
  # level that attribute actually provides.
  parts = lib.splitString "." cfg.version;
  pinnedPatch = lib.length parts > 2;
  series = lib.concatStringsSep "." (lib.take 2 parts);
  attr = "linux_${lib.replaceStrings [ "." ] [ "_" ] series}";

  havePin = pins.series ? ${series};
  pin = pins.series.${series};

  # Only the selected series is fetched; the rest of the table stays untouched.
  set =
    (import
      (fetchTarball {
        url = "https://github.com/NixOS/nixpkgs/archive/${pin.rev}.tar.gz";
        inherit (pin) sha256;
      })
      {
        inherit (pkgs.stdenv.hostPlatform) system;
        inherit (config.nixpkgs) config;
      }
    ).linuxKernel.packages;

  # hasAttr as well as tryEval: tryEval does not catch a missing-attribute
  # error, only the `throw` nixpkgs leaves behind for an EOL kernel. Guards a
  # hand-edited or stale table.
  present = havePin && set ? ${attr} && (builtins.tryEval set.${attr}.kernel.version).success;

  # Each `||` short-circuits, so `actual` is never forced unless the pin
  # resolved; the earlier assertions report those cases instead.
  actual = set.${attr}.kernel.version;
  exact = !present || !pinnedPatch || actual == cfg.version;

  pinned = lib.attrNames pins.series;
in
{
  options.core.kernel.version = lib.mkOption {
    type = lib.types.nullOr lib.types.str;
    default = null;
    example = "7.1.13";
    description = ''
      Pin boot.kernelPackages to this kernel, taken from the frozen nixpkgs
      revision recorded for its series in kernel-pins.json rather than the main
      nixpkgs. Use for hosts with out-of-tree modules (nvidia) that break on
      minor kernel bumps.

      A series ("7.1") accepts whatever patch level the pinned revision
      carries. A full version ("7.1.13") additionally asserts that patch level,
      so refreshing the table underneath fails loudly instead of silently
      moving the kernel.

      Null leaves the host on core/boot.nix's linuxPackages_latest default.
    '';
  };

  config = lib.mkIf (cfg.version != null) {
    assertions = [
      {
        assertion = havePin;
        message = ''
          core.kernel.version = "${cfg.version}" needs series ${series}, which
          kernel-pins.json does not carry.
          Pinned series: ${lib.concatStringsSep ", " pinned}
          Run `task kernel:pin` to refresh the table; it sweeps every series at
          or above the floor recorded in kernel-pins.json (currently
          ${toString (pins.minMajor or 7)}).
        '';
      }
      {
        assertion = !havePin || present;
        message = ''
          kernel-pins.json pins series ${series} at ${pin.rev}, but ${attr} does
          not resolve there. The table is stale or hand-edited; regenerate it
          with `task kernel:pin`.
        '';
      }
      {
        assertion = exact;
        message = ''
          core.kernel.version = "${cfg.version}" asks for that exact patch
          level, but the pinned revision for ${series} provides ${actual}.
          Either set it to "${actual}", drop the patch component to track the
          series, or refresh the table with `task kernel:pin`.
        '';
      }
    ];

    # mkIf's content is lazy, so a bad version surfaces as an assertion above
    # rather than nixpkgs' bare EOL throw.
    boot.kernelPackages = lib.mkIf present set.${attr};
  };
}
